version: '3.9'

services:
  app:
    image: "oven/bun:debian"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bunx prisma generate && bun run --watch src/index.ts'"
    ports: [ "3000:3000" ]
    volumes: [ "./:/home/bun/app" ]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024M"
